Move test to node test framework
fastify/fastify-accepts-serializer pull request #110
Opened 2024-09-26 18:39 UTC by allevo

Hi!
I moved the test suite from tap to node test framework.

#### Checklist

- [x] run `npm run test`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-09-26 19:11 UTC, Uzlopak commented on package.json
> +    "@types/node": "^20.11.1",
do we need types?

2024-09-26 19:11 UTC, Uzlopak commented on test/test.js
> -  t.plan(4)
we can have t.plan in node 20 and 22

2024-09-26 19:12 UTC, Uzlopak commented on test/test.js
> +    assert.deepStrictEqual(res.headers['content-type'], 'application/yaml')
if you use t.plan you have to do t.assert.deepStrictEqual

2024-09-26 22:51 UTC, dancastillo commented on package.json
> +    "test:unit": "c8 node --test test/*.js",
Lets add `--100` for coverage
```suggestion
    "test:unit": "c8 --100 node --test test/*.js",
```

2024-09-28 10:09 UTC, mcollina approved these changes
lgtm

2024-09-28 10:16 UTC, gurgunday requested changes
https://github.com/fastify/fastify-accepts-serializer/pull/110#discussion_r1777820777

2024-10-03 17:54 UTC, dancastillo commented on test/test.js
>  const test = t.test
nit import test on same line
```suggestion
const { test } = require('node:test')
```

2024-10-03 17:54 UTC, dancastillo commented on test/test.js
Related to this comment: https://github.com/fastify/fastify-accepts-serializer/pull/110#discussion_r1777614161

Use test context assert [ref](https://nodejs.org/api/test.html#contextassert)

Example: 
```js
test('Test Name', t => {
  t.plan(1) // plan
  // stuff
    t.assert.strictEqual(value, expectedValue) // asset
})
```

Example with nested tests: 
```js
test('Test Name', async (t) => {
  t.plan(2)

  await t.test('Test Name', t => {
    t.plan(1) // plan
    // stuff
    t.assert.strictEqual(value, expectedValue) // assert
  })

  await t.test('Test Name', t => {
    t.plan(2) // plan
    // stuff
    t.assert.strictEqual(value, expectedValue) // assert
    t.assert.deepStrictEqual(objValue, expectedObjValue) // assert
  })
})
```

2024-10-03 17:54 UTC, dancastillo commented on test/test.js
> +const assert = require('node:assert')
remove `node:assert` in favor of test context assert [ref](https://nodejs.org/api/test.html#contextassert)

2024-12-14 08:45 UTC, Eomm commented
Any update on this @allevo ?

2025-01-13 07:16 UTC, Fdawgs commented
Superseded by #124

2025-01-13 07:16 UTC, closed without merging